### ISSUE TITLE
increase/decrease effect using mouse wheel

### ISSUE THREAD

**Issue by wbolster** [amarovita/tint-all#2]
first of all, thanks, i sometimes prefer grayscale displays and this extension works great for that.

that said, it would be cool if the effect can be increased/decreased using the mouse wheel, e.g. slight desaturation to full desaturation.

**Comment by amarovita** [comment]
I can not find the way of how to do so. There is no any appropriate property in Clutter.ColorizeEffect class. And nothing changes if i change alpha component of the color.

**Comment by wbolster** [comment]
for colorising you may be right. for desaturation there seems to be a `factor` property:

https://developer.gnome.org/clutter/stable/ClutterDesaturateEffect.html#ClutterDesaturateEffect--factor

**Comment by amarovita** [comment]
Well it seems like we can try to use brightness/contrast in conjunction with desaturation to emulate colorize effect. And we can use factor then. But i can't find out formula yet =)))

**Comment by amarovita** [comment]
@wbolster 

Ok. I committed version with fx overwritten. Now you can change fx level for every effect. Just scroll with mouse wheel. I'll repack extension after some additional changes. May be =)

**Comment by wbolster** [comment]
awesome!
